/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package command-line-arguments */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "c_bindings.go"

#include <stdint.h>
#include <stdlib.h>

// 定义 C 接口结构体
typedef struct {
    void* dbManager;
} SfsDbManager;

typedef struct {
    void* table;
} SfsTable;

typedef struct {
    void* iterator;
} SfsIterator;

typedef struct {
    void* records;
    int count;
} SfsRecords;

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif


// 导出函数：初始化数据库管理器
//
extern __declspec(dllexport) SfsDbManager* SfsDbInit(char* dbPath);

// 导出函数：关闭数据库管理器
//
extern __declspec(dllexport) void SfsDbClose(SfsDbManager* manager);

// 导出函数：创建或打开表
//
extern __declspec(dllexport) SfsTable* SfsDbCreateTable(SfsDbManager* manager, char* tableName);

// 导出函数：设置表字段
//
extern __declspec(dllexport) int SfsDbSetFields(SfsTable* table, char** fieldNames, char** fieldTypes, int fieldCount);

// 导出函数：创建主键索引
//
extern __declspec(dllexport) int SfsDbCreatePrimaryKey(SfsTable* table, char* indexName, char* fieldName);

// 导出函数：创建普通索引
//
extern __declspec(dllexport) int SfsDbCreateNormalIndex(SfsTable* table, char* indexName, char* fieldName);

// 导出函数：插入数据
//
extern __declspec(dllexport) int64_t SfsDbInsert(SfsTable* table, char** fieldNames, char** fieldValues, int fieldCount);

// 导出函数：搜索数据
//
extern __declspec(dllexport) SfsIterator* SfsDbSearch(SfsTable* table, char** fieldNames, char** fieldValues, int fieldCount);

// 导出函数：获取记录
//
extern __declspec(dllexport) SfsRecords* SfsDbGetRecords(SfsIterator* iterator);

// 导出函数：获取记录数量
//
extern __declspec(dllexport) int SfsDbGetRecordsCount(SfsRecords* records);

// 导出函数：释放迭代器
//
extern __declspec(dllexport) void SfsDbReleaseIterator(SfsIterator* iterator);

// 导出函数：释放记录
//
extern __declspec(dllexport) void SfsDbReleaseRecords(SfsRecords* records);

// 导出函数：批量插入数据（带自动增值）
//
extern __declspec(dllexport) int64_t* SfsDbBatchInsertInc(SfsTable* table, char** records, int recordCount);

// 导出函数：批量插入数据（无自动增值）
//
extern __declspec(dllexport) int64_t* SfsDbBatchInsertNoInc(SfsTable* table, char** records, int recordCount);

// 导出函数：更新数据
//
extern __declspec(dllexport) int SfsDbUpdate(SfsTable* table, char** fieldNames, char** fieldValues, int fieldCount);

// 导出函数：删除数据
//
extern __declspec(dllexport) int SfsDbDelete(SfsTable* table, char** fieldNames, char** fieldValues, int fieldCount);

// 导出函数：范围搜索
//
extern __declspec(dllexport) SfsIterator* SfsDbSearchRange(SfsTable* table, char** startFieldNames, char** startFieldValues, char** limitFieldNames, char** limitFieldValues, int fieldCount);

#ifdef __cplusplus
}
#endif
